CREATE TABLE IF NOT EXISTS categories (
  category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(50) NOT NULL,
  CONSTRAINT pk_category PRIMARY KEY (category_id),
  CONSTRAINT uq_categories_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(250) NOT NULL,
  email VARCHAR(254) NOT NULL,
  CONSTRAINT pk_user PRIMARY KEY (user_id),
  CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events (
event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
annotation VARCHAR(2000) NOT NULL,
category_id BIGINT NOT NULL,
description VARCHAR(7000) NOT NULL,
event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
published_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
user_id BIGINT NOT NULL,
location_lat REAL NOT NULL,
location_lon REAL NOT NULL,
paid BOOL NOT NULL,
participant_limit INT NOT NULL,
request_moderation BOOL NOT NULL,
title VARCHAR(120) NOT NULL,
state VARCHAR(20) NOT NULL,
CONSTRAINT pk_event PRIMARY KEY (event_id),
CONSTRAINT fk_events_to_categories FOREIGN KEY(category_id) REFERENCES categories(category_id) ON DELETE RESTRICT,
CONSTRAINT fk_events_to_users FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests (
request_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
event_id BIGINT NOT NULL,
user_id BIGINT NOT NULL,
status VARCHAR(20) NOT NULL,
created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
CONSTRAINT pk_request PRIMARY KEY (request_id),
CONSTRAINT fk_requests_to_users FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE,
CONSTRAINT fk_requests_to_events FOREIGN KEY(event_id) REFERENCES events(event_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations (
compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
pinned BOOL NOT NULL,
title VARCHAR(50) NOT NULL,
CONSTRAINT pk_compilation PRIMARY KEY (compilation_id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
compilation_id BIGINT NOT NULL,
event_id BIGINT,
CONSTRAINT fk_compevents_to_compilations FOREIGN KEY(compilation_id) REFERENCES compilations(compilation_id) ON DELETE CASCADE,
CONSTRAINT fk_compevents_to_events FOREIGN KEY(event_id) REFERENCES events(event_id) ON DELETE SET NULL
);

